### ISSUE TITLE
`type` parameter in Adapter methods has incorrect type

### ISSUE THREAD

**Issue by gitKrystan** [typed-ember/ember-cli-typescript#1296]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [x] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### Now about that bug.

The `type` parameter in Adapter methods has the incorrect type. For example:

```ts
findRecord<K extends keyof ModelRegistry>(
    store: Store,
    type: ModelRegistry[K],
    id: string,
    snapshot: Snapshot<K>
): RSVP.Promise<any>;
```

The `type` parameter has the type of `ModelRegistry[K]` which would be resolved to something like `User` or `Post`. In other words, it is claiming to receive an _instance_ of the given model. In reality, these methods receive the model's _class_, not an instance.

For example, in `findRecord`, if one tried to do `type.modelName` (`modelName` is a static property on the `Model` class), they would get a type error of `Property 'modelName' does not exist on type 'ModelRegistry[K]'`. On the other hand, you would get no errors when calling `type.save()`.

Probably, the best we can do here is `type: typeof Model`. 😢

**Comment by chancancode** [comment]
We could add a `ModelClassRegistry`, but it doesn't seem like the utility is there to be worth the extra boilerplate

**Comment by chriskrycho** [comment]
Ahhh, this makes sense. I think I wrote that type, and I wasn't super clear from the docs at the time whether it was supposed to be a class or an instance.

It should actually be possible to write this correctly by making it `Constructor<ModelRegistry[K]>` instead of `ModelRegistry[K]`; we may even have a utility type for `Constructor` already, but it's straightforward enough to write one if not.

**Comment by chriskrycho** [comment]
Note that there's also an additional issue here in that it's actually *always* an unsafe cast using the generic *or* an unsafe "narrowing" via a type definition on the actual `type` argument here, since there's no way for an adapter method *in general* to know which type it's being passed. We might actually be better off just typing it as `Constructor<Model>`, and requiring users to do whatever runtime checking is required accordingly.

**Comment by chriskrycho** [comment]
Doh, further follow-up: I realize now that even doing `Constructor<Model>` doesn't give us what we need; it's on the static side of the class IIRC?

**Comment by chriskrycho** [comment]
Annnnd one last note: we may at some point (when we are making other sweeping, massive, breaking changes to the types… perhaps by pulling them out of DT into our own direct control) want to make *all* registries work with `name: typeof Type` instead of `name: Type`, because it means you can always get at *both* types as you need them. E.g. here you would just end up doing `ModelRegistry[K]` and then the `store.findRecord` lookup would return you `InstanceOf<ModelRegistry[K]>` instead, and 💥 now you can use either as needed. (This is what I proposed for the types for the rejiggered registry APIs in emberjs/rfcs#0585, for precisely this reason.)

**Comment by chancancode** [comment]
Yeah, I don't think `Constructor<Model>` is useful, it's not the ability to construct the types that is useful here, it's the metadata and other class methods that you want, which is why we suggested `typeof Model`.

**Comment by chancancode** [comment]
Seems like `store.modelFor` and the equivalent places in the serializer is also wrong for the same reason.

**Comment by chancancode** [comment]
Also `snapshot.type`

**Comment by chriskrycho** [comment]
Yeah, agreed about `Constructor`—you just got to see my *whole* train of thought as I worked that out in between other tasks yesterday.

Makes sense that all of the related pieces are wrong, as I think I simply misunderstood the docs when I built out the type defs originally (about 3 years ago)—the Data docs were in *much* worse shape then.

**Comment by chancancode** [comment]
Seems like this is fixed now
