### ISSUE TITLE
@types/ember is not used for auto completion

### ISSUE THREAD

**Issue by mydea** [typed-ember/ember-cli-typescript#1341]
I have been wondering for a while why I was not getting any auto complete suggestions for any `@ember/...` packages in VSCode. After some playing around, I found out that it only seems to provide auto-complete for direct dependencies defined in the package.json file. Since all the ember types are actually provided as sub-dependencies via `@ember/types`, they are not used. After I replaced `@types/ember` with the full list from there:

```
{
        "@types/ember__application": "*",
        "@types/ember__array": "*",
        "@types/ember__component": "*",
        "@types/ember__controller": "*",
        "@types/ember__debug": "*",
        "@types/ember__engine": "*",
        "@types/ember__error": "*",
        "@types/ember__object": "*",
        "@types/ember__polyfills": "*",
        "@types/ember__routing": "*",
        "@types/ember__runloop": "*",
        "@types/ember__service": "*",
        "@types/ember__string": "*",
        "@types/ember__template": "*",
        "@types/ember__test": "*",
        "@types/ember__utils": "*",
        "@types/htmlbars-inline-precompile": "*",
        "@types/jquery": "*",
        "@types/rsvp": "*"
}
```

(Replacing the stars with actual versions)

Auto complete worked like a charm. For me as a non-TS-expect, that was rather unexpected.

* As a developer, I want to get autocompletion for ember packages out of the box after installing ember-cli-typescript

Would it make sense to either install these directly instead of `@types/ember`? It _is_ a bit sub-ideal that it kind of bloats up your package.json, but if this is what is needed for auto-complete I'll gladly take it.

**Comment by chriskrycho** [comment]
Thanks for filing this! The problem is that TS *intentionally* does not suggest imports from transitive dependencies, since it's not safe to depend on them; but Ember supplies its packages… as transitive dependencies. (That's not even *really* what's happening today; it's still relying on build-time magic transforms of imports, but that's notionally what's happening, and presumably/hopefully what the future holds.) We need to update our blueprints to explicitly install the `@types/ember__*` dependencies as well as `@types/ember`, and the same for `@types/ember-data__*` as well as `@types/ember-data`.

**Comment by mydea** [comment]
If you're willing to accept this, I'd be happy to update the blueprints accordingly!

**Comment by chriskrycho** [comment]
Yes please!
