### ISSUE TITLE
Docs on "Using TS Effectively" are wrong about blueprint value of "noEmitOnError"

### ISSUE THREAD

**Issue by gabrielgrant** [typed-ember/ember-cli-typescript#1402]
The docs on "Using TS Effectively" say "noEmitOnError" default is `true` (and suggest leaving this value as-is): https://github.com/typed-ember/ember-cli-typescript/blame/master/docs/ts/using-ts-effectively.md#L30

It seems the actual value in the blueprint is `false`, though: https://github.com/typed-ember/ember-cli-typescript/blob/master/blueprint-files/ember-cli-typescript/tsconfig.json#L16

Seems likely this docs line should be replaced with an explanation of why the value is as it is, and when to change it (or, if it really is a good idea to have it enabled, perhaps the blueprint value should be changed?)

**Comment by dfreeman** [comment]
Thanks for catching this discrepancy, @gabrielgrant!

The Typed Ember team had discussed changing the default value in the blueprint to `true` a long while back, and (as you discovered) even documented it as such, but it turns out we never actually made the change 😅 

We should definitely update the blueprint accordingly. If you have the chance to open a PR, that would be welcome! Otherwise one of the maintainers will aim to get this squared away soon.

**Comment by gabrielgrant** [comment]
thanks for clarifying and fixing!
