### ISSUE TITLE
Question - tslint to eslint migration

### ISSUE THREAD

**Issue by IgorKvasn** [typed-ember/ember-cli-typescript#1412]
I am trying to migrate from TSlint to ESlint - I tried following several tutorials on how to do it, but it looks like whatever I do, TSlint always runs (at least according to console output when I run `ember s` there are linting errors with TSlint codes like this: `TS2769: No overload matches this call.`).

Could you please give me some hints, how to properly configure eslint to lint typescript files and disable tslint?

thanks a lot

(Another funny thing is that, there is no TSlint package installed in my node_modules, so I don't understand how come tslint is run)

**Comment by chriskrycho** [comment]
Hi @IgorKvasn – are you still having problems with this? (And sorry for the delay!)

**Comment by IgorKvasn** [comment]
Hi, yes - I still cannot get rid of tslint :(

**Comment by boris-petrov** [comment]
@IgorKvasn - you can search `package-lock.json` or `yarn.lock` for `tslint`. It should come from somewhere. `ember-cli-typescript` doesn't install it.

**Comment by dfreeman** [comment]
@IgorKvasn is it possible you're talking about TypeScript itself rather than TSLint? Type errors come like the one you mentioned come from the TS typechecker itself, while TSLint was meant to be a tool akin to ESLint for enforcing codebase consistency and catching "this probably isn't doing what you think it is" sorts of likely-errors.

Since ESLint now understands TypeScript syntax, TSLint has been deprecated with a migration path to ESLint, but as far as I know it's not generally recommended (or perhaps even possible) to have ESLint drive typechecking.

**Comment by IgorKvasn** [comment]
@dfreeman  I looked though [tslint rules](https://palantir.github.io/tslint/rules/) and none of the console errors I receive seem to be result of failing tslint rules - so it looks like you are right, those are TS typechecker errors and not tslint... so I guess I was trying to disable tslint that wasn't actually enabled at all :)
thanks a lot
