### ISSUE TITLE
Creating PromiseArray using constructor syntax not working?

### ISSUE THREAD

**Issue by Bouke** [typed-ember/ember-cli-typescript#1432]
### Which package(s) does this problem pertain to?
  - [x] @types/ember-data

I have a list of IDs and I want to get a ember-compatible promise object that resolves to an array of objects. Very similar to what `findAll('person')` would return. Using the `new` syntax this doesn't appear to work:

```ts
const ids = ["1", "2"];
const selected = ids.map(id => this.store.findRecord('person', id));
const p = new DS.PromiseArray<Person>();
p.promise = all(selected);
this.selected = p;
```

When used it'll give a runtime exception "tag is undefined".

When I create an instance using the `.create()` syntax, it works just fine. I was under the impression that I could just substitute `.create` with `new`, but this is apparently not always the case? How would I know, does it require trial-and-error?

```ts
const ids = ["1", "2"];
const selected = ids.map(id => this.store.findRecord('person', id));
const p = DS.PromiseArray.create({ promise: all(selected) });
this.selected = <DS.PromiseArray<Person>>p;
```

I've updated to the latest typings:
- @types/ember 3.16.5
- @types/ember-data 3.16.13

I'm running ember/-data 3.25.

**Comment by chriskrycho** [comment]
This is not an ember-cli-typescript issue; it’s an issue in terms of the APIs of underlying Ember objects. In general, you should stick to what is documented in Ember’s own official docs. The type definitions for Ember’s types don’t *prevent* you from trying something like this: though in principle they could possibly be made to, that would be more work than it’s worth maintenance-wise.

As an aside, in this case, I would also generally not recommend the pattern you’re using; `PromiseArray` and `PromiseProxy` aren’t especially good patterns, and Ember Data itself is slowly moving away from them. You’d be better off going the *other* direction: compose a new type using `RSVP.all` (or just `Promise.all`) instead, so that you end up with normal Promise and Array semantics instead of coupling yourself to Data’s quirky semantics.
