### ISSUE TITLE
Published NPM package is 533MB because of node_modules.before and node_modules.after directories

### ISSUE THREAD

**Issue by jakesjews** [typed-ember/ember-cli-typescript#1435]
These directories appear to be accidentally published in the last package update

**Comment by musaffa** [comment]
All of my Heroku builds are failing because of this. From Heroku shell:

![Screenshot from 2021-06-17 15-15-28](https://user-images.githubusercontent.com/294616/122368232-f816ba00-cf7e-11eb-8083-f7b4835cf5de.png)

In `node_modules`, @ember has become 561 megabyte in size! It was only 2.9 megabyte previously.

@chriskrycho Please have a look at this.

**Comment by jamescdavis** [comment]
Fixed in [4.2.1](https://github.com/typed-ember/ember-cli-typescript/blob/master/CHANGELOG.md#421---2021-06-17). Sorry about that!!!
