### ISSUE TITLE
Controller param types in route hooks don't pass type checks

### ISSUE THREAD

**Issue by theroncross** [typed-ember/ember-cli-typescript#1493]
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [x] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support

>> Your Instructions Go Here <<
ember g controller application
```
```js
// controllers/application.js
...
someProp = true;
...
```

```js
// routes/application.js
import ApplicationController from '../controllers/application';
...
setupController(controller: ApplicationController) {
  controller.someProp = false;
}
...
```
##### Reproduction Case
If you can, please try to fork [this codesandbox](https://codesandbox.io/s/github/mike-north/ember-new-output/tree/ts), and give us an example that demonstrates the problem. Paste the link below so that we can see what's going on

**Link: ** <your link here>

### Now about that bug. What did you expect to see?
setupController should pass type check

### What happened instead?
```
Property 'setupController' in type 'ApplicationRoute' is not assignable to the same property in base type 'Route<unknown, object>'.
  Type '(controller: ApplicationController) => void' is not assignable to type '(controller: Controller, model: unknown, transition: Transition<unknown>) => void'.
    Types of parameters 'controller' and 'controller' are incompatible.
      Type 'Controller' is missing the following properties from type 'ApplicationController': someProp(2416)
```

**Comment by theroncross** [comment]
I'm not sure which yet, but we might have been using some outdated dependencies, as it now seems to be working as expected.

**Comment by bartocc** [comment]
ah… I'll have to try and update some deps too then to find what happened…

**Comment by joshuaswift** [comment]
I'm experiencing this issue also, @bartocc did you manage to track down which dependency was causing it?

**Comment by chriskrycho** [comment]
FWIW, I've confirmed this issue does not exist with Ember's [own types][source] *or* the latest version of [the types on DefinitelyTyped][DT], so I'm going to mark this issue as *closed*, with the following recommendations as paths forward:

1. Switch to using Ember's own preview and stable types, as documented [here][blog].

2. Make sure you only have a single copy of the latest version of the various `@types` packages in your project if still using the DT types—remove any duplicate entries from your lock file and re-run `npm install`, `yarn`, etc.

If those don't help, feel free to continue commenting here, but note that I *am* going to mark the issue as closed since I can confirm it's not an issue with the types themselves.

[source]: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgKYgEZKgWgM4QK5QDGSA9DAJ5hLYIDcAUKJLIiulrgcWZdSWFCQA3YEgDudeo3DR4AYQgA7GFAgAbNRjgAzVSEQABNhhKElK9ZqiSmsuACV8MJDr2HjUEqrwxgigOZeTkiS9IRqAIbY2HAAogAeEeCaCsqqGlpI8c6KACYxqRYZUHAA3vRwlXC4IEgACqpgcAC8cCp4SAwAvlLhUTEJSWCajj4uWTn5DsFlFVXYSDB4YIXpVgAUZmmWGABccYnJSKs7UACUs1VXcFtFVgB0NfWNLToRagsMVz1dQA
[DT]: https://www.typescriptlang.org/play?#code/PTAEAEBcGcFoEsDmA7A9gJwKYCh4FsAHDSUAcigE8DNphM8AjTdAfRYGNVlJ1UAbPs1IBubCAgwEKDDnxF0JcpCo06jZm14BXSPGSIR2XIWKgAwlx79B6UADNeeMuHpN0wTt14ChouaYAlVB1Me0dnV2ZgbV19aODITENsdj4AQ2hoUABRAA80wkELL2tmUExcxOQAEyziqx9bAG9sUDbQaFQ8TAAFXgJQAF5QHi1MUQBfI1SMrLyCgkEgkPLKzBqs5cTQFvaOzEgtAnrvGwAKTwabAC4c-MLME9L0AEod1r32y9PmADpO7p9VADYZ2NJ8aDjD5tKYTIA
[blog]: https://blog.emberjs.com/announcing-official-typescript-types-public-preview

**Comment by bartocc** [comment]
We are in the process of upgrading to 

> Ember's [own types](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgKYgEZKgWgM4QK5QDGSA9DAJ5hLYIDcAUKJLIiulrgcWZdSWFCQA3YEgDudeo3DR4AYQgA7GFAgAbNRjgAzVSEQABNhhKElK9ZqiSmsuACV8MJDr2HjUEqrwxgigOZeTkiS9IRqAIbY2HAAogAeEeCaCsqqGlpI8c6KACYxqRYZUHAA3vRwlXC4IEgACqpgcAC8cCp4SAwAvlLhUTEJSWCajj4uWTn5DsFlFVXYSDB4YIXpVgAUZmmWGABccYnJSKs7UACUs1VXcFtFVgB0NfWNLToRagsMVz1dQA)

I'll make sure we don't have this issue anymore after that
