### ISSUE TITLE
Provide CLI option for `tsconfig.json` path to allow different config per env

### ISSUE THREAD

**Issue by hamish-later** [typed-ember/ember-cli-typescript#1513]
### Please write a user story for this feature

Follow the form

> *As a **role**, I want **feature** so that **reason**.* 

> Example: 
>
> As an **addon publisher**, I want tobe able to **precompile my addon's typescript into js**, so that **my consumers can use my code, regardless of whether their app is written in typescript**

As a developer, I want to be able to specify different `tsconfig.json` file paths upon serving my app, so that my team can extend our base config and override environment-specific TypeScript options. For example, exclude paths and includes related to testing from our base `tsconfig.json`, but include them in `tsconfig.test.json`.

**Comment by chriskrycho** [comment]
@hamish-later just saw this – sorry for the long delay. I'm not *positive* this makes sense as a CLI feature for Ember specifically to maintain, in particular because all the different configurations and environments folks end up needing can vary dramatically. I'm going to close this accordingly.

However, you should not take that as meaning it's a *hard no* here, only that it's not really scoped well as a request at present. If you are passionate about this and interested in driving it forward (and potentially implementing it), an RFC would be a good starting point!
