### ISSUE TITLE
Best practices regarding observers?

### ISSUE THREAD

**Issue by alankila** [typed-ember/ember-cli-typescript#156]
It seems I need to call object's extend() to get Ember observers to work the usual way, e.g. something like this seems to work fine:

```ts
export default class MyComponent extends Component.extend({
    somepropertyObserver: observer("someproperty", function(this: MyComponent) {
       ...
    }),
}) {
    ... define the rest of the class here ...
}
```

However, if defined in the class body as usual, they do not get called when someproperty updates. Clearly, observers are specially handled at some earlier phase of object construction.

```ts
    constructor() {
        this.addObserver("someproperty", this, this.somepropertyObserver); 
    }

    somePropertyObserver(this: MyComponent) {
        ...
    }
```

As a point of interest, I noticed that this observer is not yet functional after constructor returns. E.g. if I try to change the "someproperty" right after registering an observer for it, the observer doesn't fire. This suggests that it's not the object itself that makes the observers work, but rather that there is some other part of Ember that actively looks for observers defined for an object, and calls them in some circumstances. This, in turn, raises questions about all the places these observers might get propagated to, and whether they will leak memory unless I manually remove them when object gets disposed.

I wonder if I should turn each property being observed into a computed property that runs the observer during its set(), e.g. something like this:

```ts
function defineObserver<T>(callback: (newValue: T | undefined, oldValue: T | undefined) => void): ComputedProperty<T> {
  let value: T | undefined;
  return computed({
      get() { return value; },
      set(_key: string, newValue: T) { callback(newValue, value); value = newValue; return newValue; },
  });
}
```

and if I need an observer for a property that is already a computed property, then maybe I should just fire the observers from its set().

**Comment by chriskrycho** [comment]
I don’t have time to dig in deeply on observers today, but I’ll just note that the recommendation in *general* in Ember is to avoid observers, because it’s difficult to make sure you get them torn down correctly, and very nearly everywhere you’d use them, use of a computed property does the job both more clearly and more cleanly anyway.

I think it *is* the case that observers need to be installed on the prototype, so if you have places you can’t switch directly to computeds, doing them in an `.extend({ ... })` is the right move—that’s what we’ve observed in our own app as well, though I think right now we’re down to one observer and that’s in a component we’ve just deprecated and will be removing shortly!

In general, my own preference is also to define a chain of computed properties rather than using `set` in computeds at all.

**Comment by chriskrycho** [comment]
(Closing since this is a general Ember issue, not a TS issue, but feel free to continue chatting through any observer-specific issues here!)
