### ISSUE TITLE
Types in the @types dir not picked up

### ISSUE THREAD

**Issue by nicolaidahl** [typed-ember/ember-cli-typescript#185]
Hi there

In my project, I'm using the classnames npm package, which has types defined at `node_modules/@types/classnames`. When importing classnames:
```
import classNames from 'npm:classnames';
```
I can make the usual, cannot find module, error go away by adding it to paths in the tsconfig file:
```
"paths": {
      "npm:classnames": ["./node_modules/classnames"]
}
```
However, VSCode and WebStorm still complains about not being able to find the types
"Could not find a declaration file for module 'npm:classnames'"

If I rename the `node_modules/@types/classnames` directory to 'node_modules/@types/npm:classnames`, Typescript picks up the types perfectly. This has other obvious problems though.

I have verified that this is not a problem specific to the classnames package. Any package that has its types specified externally in the @types folder doesn't seem to work with Ember and the ember-browserify way of doing imports.

Any known solution to this problem? Any help is much appreciated.

Thanks for this repo

**Comment by chriskrycho** [comment]
**First**, thank you for the report and sorry it took us a couple days to get back to you!

**Second,** To summarize and make sure I’m understanding: what you’re seeing is that you have some package `a` which has types available at `@types/a`, and which you’re importing via ember-browserify, so you’re doing `import a from 'npm:a';` as usual in ember-browserify… but because the paths don’t match for `@types` and the actual *or* mapped import path, you don’t get type resolution.

That all makes sense, unfortunately, and I don’t know of any way around it that I’m *certain* will work. You might try this, though:

```json
"paths": {
    "npm:a": ["./node_modulues/a", "./node_modules/@types/a"]
}
```

Again, I can by no means guarantee that’ll work, but it’s the only thing I can think of which *might*. Can you try that and let us know?

**Comment by nicolaidahl** [comment]
Well spotted @chriskrycho. That seems to have done the trick! Thanks a lot :)

**Comment by chriskrycho** [comment]
I'll add a note to document this.
