### ISSUE TITLE
assert doesn't fix 'object is possibly null'

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/ember-cli-typescript#197]
![image](https://user-images.githubusercontent.com/199018/39301496-4196bf72-491d-11e8-845c-0bbe0bd2a316.png)

hovering over the red squggly, it says: `[ts] Object is possibly 'null'.`

shouldn't assert tell ts that it's not possible?

**Comment by chriskrycho** [comment]
I originally thought the same, but until TS 2.8, the type system itself didn't give you enough info to make it work. (The type of `assert` *itself* doesn't tell you anything about the types in play.) If you're using TS 2.8, this definition of `assert` works – we will ultimately get it into the types, but not until we bump to supporting only 2.8+.

```ts
declare module '@ember/debug' {
  declare function assert<T extends boolean>(
    desc: string,
    test?: T
  ): T extends true ? void : never;
}
```

Unfortunately I don't know of any way to supply that "override" locally for this kind of type definition (because it's not an interface, and doesn't get merged properly; it just ends up looking like a conflicting definition to TS).

**Comment by dfreeman** [comment]
That works? I was under the impression TS's control flow analysis wasn't able to perform type narrowing based on a `never` return type https://github.com/Microsoft/TypeScript/issues/8655

**Comment by chriskrycho** [comment]
You're correct, @dfreeman – the bit I outlined above had *appeared* to work in a case where TS had actually been narrowing because I supplied a literal (`let f: string | undefined = 's';` is a `string`, *not* `string | undefined`). Very annoying.

**Comment by mike-north** [comment]
Removing [bug] because this is just a consequence of the way TypeScript works.

**Comment by phil294** [comment]
Looks like there is no other way than to explicitly cast `this.channel = this.channel as Channel` below the assert statement

**Comment by chriskrycho** [comment]
That’s correct. I’m actually going to close this since there’s nothing in the language to solve this at this point.
