### ISSUE TITLE
PromiseProxyMixin uses RSVP.Promise which is incompatible with native Promises

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#341]
We discussed this in these two comments - [here](https://github.com/emberjs/ember.js/issues/17021#issuecomment-429298736) and [here](https://github.com/emberjs/ember.js/issues/17021#issuecomment-429570531).

The problem is that `PromiseProxyMixin` uses `RSVP.Promise` in its type definition which makes it impossible to work with in TypeScript using native promises. And because Ember.js will be moving away from using RSVP at some point, this has to be figured out.

**Comment by chriskrycho** [comment]
In the typings we've written, we've made a point to capture what the types *actually are*, and so long as Ember is using RSVP, we want the types to model that accurately (so we won't be changing them any time soon!).

It's often possible to use `PromiseLike<T>` instead of `Promise<T>` in your types, thought that doesn't solve behavior around `async` or `await`. It's also fine to do a type-cast: `as Promise`. `RSVP.Promise` is (by definition of its conformance to the A+ Promises spec) a strict superset of the native `Promise` type, and so will work *for type purposes* as a native `Promise`. In short, you should be able use an `RSVP.Promise` anywhere native `Promise` is desired, but not necessarily vice versa.

**Comment by mike-north** [comment]
It might be nice to have a section of the docs describing how one might override this kind of thing in their own project

For world-class web developer training: https://mike.works
________________________________

**Comment by chriskrycho** [comment]
This has largely been resolved by way of a few changes:

1. We improved the types in this space (esp. for RSVP’s `Promise` compatibility) over time as TS afforded it.
2. We changed how we represent mixins, especially in Ember's stable types.
3. The Ember ecosystem has *almost* entirely moved away from `PromiseProxyMixin`, and it is in a position that it could be deprecated with effectively no churn.

Closing this accordingly!
