### ISSUE TITLE
Question about the state of work

### ISSUE THREAD

**Issue by KillaPL** [typed-ember/ember-cli-typescript#37]
Hey guys, great work on integrating typescript!

I have a question about how things are going. I have seen presentation at https://www.youtube.com/watch?v=951HiqnNQ1w, and googled this repository as the only existing integration with typescript.

In the presentation, the presenter is showing type checking with `get` functions, and even suggesting of what can be used inside `get`, however this doesn't seem to be the case for me. Typescript doesn't seem to recognize that `get` is a function, and that there is a set of acceptable inputs. Am I doing something wrong in here, or is this level of integration still not achievable?

**Comment by chriskrycho** [comment]
@KillaPL very fair question! As far as I know, that working the way it does there depends on some stuff @DanielRosenwasser had started on, but which hasn't yet landed in the @types for Ember yet. I'm not sure what the status is on those, and haven't yet had time to pick up that work myself.

**Comment by KillaPL** [comment]
Ah, I see, so this is ongoing work. Very well, I'll wait paitiently wait until this is available. Or is there anything we can do to help?

**Comment by chriskrycho** [comment]
@KillaPL I'm going to try to figure out a plan for getting this moving, and will probably write up an issue with my thoughts once I have that. (I've been on vacation for the last few weeks and have gone out of my way not to think about Ember or TypeScript or this add-on in that time.)

**Comment by KillaPL** [comment]
I'm quite eager to introduce typescript, assuming it will look the way it looks on mentioned presentation. Please let me know if and how I can help.

**Comment by maerten** [comment]
Hey, sorry for hijacking this issue

we have been experimenting with TypeScript 2.x features and created an addon similar to ember-cli-typescript (at https://github.com/draios/ember-typescript2 )

We plan to ultimately contribute to **@types/ember** and/or **ember-cli-typescript** but at the current state our Addon is not compatible with either package.

**Our current approach splits the type into two parts:**

1. the built-in Ember stuff (Router, Component, Ember-Data, etc)
2. an application.d.ts where users define their application models, services, and injections (from app/initializers)

The application.d.ts contains a 'type index' for Models and Services, to enable type checking things like `this.store.createRecord('user')`and `Ember.service.inject('my-service');` is properly typed this way.

Curious to hear any thoughts on our 'global type index' approach!

**Comment by chriskrycho** [comment]
@maerten, getting back to you at last – sorry for the delay.

As I noted on Slack, I think there are a couple ways this diverges from the long-term approach that should best work for Ember and TypeScript integration, and they basically map to the ways you're splitting the types in two.

1. **For the built-in Ember stuff**, rather than shipping types in this add-on, it's much more helpful to ship them upstream – whether we find a way to integrate them directly into the Ember build process itself (which would be best 🤞) or just getting them solid and upstreaming them back into DefinitelyTyped. Among other things, getting the upstreamed to one of those places would make it so that people who have their own build process which uses TypeScript could do so without including your add-on (or ember-cli-typescript, equally; that's one reason I'm not trying to update the typings here in this add-on).

2. **For the application types**, the approach you have come up with *works*, and parts of it even might be worth adapting into this add-on going forward – specifically the idea of a type index for e.g. services or other things which are injected via dependency injection and the resolver. But putting it all in one global file (as you note in your comments) unnecessary we can just [merge declarations](http://www.typescriptlang.org/docs/handbook/declaration-merging.html) instead.

    The other major consideration in this area is that *when* (not *if*) ES6-style classes land (hopefully this year! 🤞again) we should be able to leverage *that* to just be able to specify the types locally on other class declarations.

That said, as we've seen in the past in the Ember community, experimentation and then convergence is a really helpful pattern – so your exploring some things in parallel (even, perhaps, running that add-on as a fork of this one for a while if you so desire) is fine by me!

**Comment by maerten** [comment]
@chriskrycho no problem at all. Thanks for sharing your thoughts, its appreciated!

To respond to your comments:

(1) I agree it would be best to integrate the generic Ember types and interfaces into DefinitelyTyped at some point. For now they seem to work pretty well with the new Typescript 2.x features, but I haven't done any actual Ember development with this yet, and they are far from complete in terms of API coverage. (Also I saw someone on #topic-typescript on Ember slack who uses tests, which is something we should have too!)

(2) Great to hear that you like the type index approach :) The thing i'm wondering about is; if we would have an addon just for the _application type indexes_, we would still need to support the idea of type indexes from \@ types/ember. 
How would that work? I think if someone uses just the 'built-in Ember stuff' declarations without the addon part, the experience would not be great. Not sure how we could even inform a user about the addon part of this.

Either way, I think you're making a good point and this is probably the way to go: (1) generic stuff in \@ types/ember, and (2) an addon for the indexes.

Thanks!
-----

_Random idea: Perhaps it would be possible to have the generic types (from @types/ember) have empty indexes as a default, so at least the typechecker doesn't complain about valid code such as `this.store.createRecord('myModel', { /* ... */ })`._

```
interface EmberServicesIndex {
   [key: string]: any
}
```
Not sure if we could override / disactivate such an interface from the _addon side_ though, if all declarations are merged in TS...

**Comment by chriskrycho** [comment]
Closing this, since we've long since resolved this discussion – but with the note that we'll probably be adopting something like the types registry @maerten pioneered for services and for Ember Data lookups sometime in the next month or two!
