### ISSUE TITLE
Documentation: Clarify that noEmitOnError will fail the build on type errors

### ISSUE THREAD

**Issue by baron1405** [typed-ember/ember-cli-typescript#753]
Please clarify the explanation of the `noEmitOnError` flag to indicate it can be used to fail the build on type errors. Specifically, in the section "Using TypeScript with Ember Effectively", "Incremental Adoption", the third bullet regarding the `noEmitOnError` should contain a sentence stating that setting this flag to `true` will fail the build on type errors.

**Comment by chriskrycho** [comment]
@baron1405 thanks for filing this (and sorry it took us over a year to respond). I'll take this into account as we revise the docs. From where I stand, this seems obvious, because that's the behavior of `tsc` itself here. I assume, however, that the confusion is the way that ember-cli-typescript integrates type-checking into the *Ember* build process?

**Comment by baron1405** [comment]
Yes, it was not obvious as I migrated.
