### ISSUE TITLE
problems using this.get

### ISSUE THREAD

**Issue by BryanCrotaz** [typed-ember/ember-cli-typescript#79]
```
[ts]
The 'this' context of type 'this' is not assignable to method's 'this' of type 'ComputedProperties<{ onStateChanged: StateChangeCallback<SlideCueManagerState>; onCued: SlideCueM...'.
```

A summary of my code...
```
import EmberObject from '@ember/object';
import { task, timeout } from 'ember-concurrency';

class MyThing extends EmberObject {
  constructor() {
    super();
    // stuff
  }

  private DoLater() {
    this.get("doLaterTask").perform();
    **// ====> FAILS TO COMPILE HERE WITH ABOVE ERROR**
  }

  private doLaterTask = task(function * () {
    yield timeout(500);
    // do stuff
  }).drop();
}

export { ISlideCueManager, SlideCueManager, SlideCueManagerState };
```

**Comment by chriskrycho** [comment]
Thanks for the report!

1. Can you re-open this against the [ember-typings repo](https://github.com/typed-ember/ember-typings) instead of here? That’s where we’ve tracked work on the type definitions.
2. Can you include the specific version of the Ember typings (`@types/ember`) you have installed?
3. I’ll follow up on this early next week; can you tighten this down to a truly minimal example (where all the names line up, etc.)? That’d be *super* helpful in figuring out the typings issue. (Also for typings stuff, in
