### ISSUE TITLE
RFC: deprecate MU support

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#806]
Given that MU has been officially [declared dead](https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html), and in the interest of eliminating at least *some* of our debt in the short term (since we unfortunately don't yet have a good solution implemented for #71), I propose we officially deprecate support and remove it in a future release.

Given we're *just about* to cut a major, I propose we cut the major and deprecate *in* the major, i.e. 3.0.0 formally deprecates MU support. In this thread, we can discuss the timeline—how long should users be guaranteed support before the deprecation becomes a breaking change by way of removal?

(Also, if there are objections, I'm up for hearing them, but I *think* this should be relatively uncontroversial; the sooner we can get MU support out of *everything* the lower everyone's maintenance burden will be!)

## Related

- [Update on Module Unification](https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html)
- typed-ember/ember-cli-typescript-blueprints#100

**Comment by dfreeman** [comment]
Sounds good to me. I _think_ this should just be a matter of updating/dropping blueprints (and optionally deleting one "custom project layout" test), since the build and typechecking pipeline is layout agnostic now.

**Comment by chriskrycho** [comment]
That's what I *thought* was the case, so glad to hear it confirmed. 👍🏼

**Comment by dfreeman** [comment]
A quick update here! Since removing MU support in `ember-cli-typescript` only amounts to blueprint changes and MU itself has been declared dead for a number of months, the Typed Ember team decided while planning for the 3.0 release to go ahead and drop the MU blueprints with 3.0.

Projects using MU should continue to build and typecheck correctly with `ember-cli-typescript@3` by virtue of the fact that we use `tsconfig.json` as the source of truth when determining project layout, but active projects still using MU may want to consider migrating anyway, given the broader ecosystem direction indicated by the posts Chris linked above 🙂

**Comment by chriskrycho** [comment]
Closing because we did this! 🎉 (…a while ago. We're, uhh, behind. 😆)
