### ISSUE TITLE
Pre-render docs for performance

### ISSUE THREAD

**Issue by chriskrycho** [typed-ember/ember-cli-typescript#927]
If we can, it'd be great to set up something like prember so that we can have a static site that works without JS, but which turns into a nice, fully-functioning Ember app after boot. This would presumably entail setting up prember during the build-and-deploy process. Relatively low priority, compared to the other things but very nice to have.

**Comment by dfreeman** [comment]
There's a conflict between prember and how addon-docs deals with its versioned deploys that makes this not-quite-possible currently, but it's something I've been meaning to work on for quite a while.

Agreed that we should prioritize getting actual doc content together, but one our upstream issue is worked out, adding prember should be super easy.

**Comment by dustinsoftware** [comment]
Managed to get this _almost_ working locally, haven't tested the deploy story yet. Current branch is [here](https://github.com/dustinsoftware/ember-cli-typescript/tree/prember). A few gotcha's so far:

1. Ran into a fastboot crash with the current version of `ember-cli-addon-docs`, which will be fixed once this makes its way into a release: https://github.com/ember-learn/ember-cli-addon-docs/pull/418

2. In my [fork of the e-c-addon-docs repo](https://github.com/dustinsoftware/ember-cli-addon-docs/tree/prember-docs), I successfully added prember with a bit of additional logic to read the generated JSON file instead of scraping the page to discover all the URLs that need to be preloaded. However, any downstream addon that takes a dependency on this repo will _also_ attempt to load the `urlsForPrember` hook. When running `ember build` from `e-c-typescript`, the `e-c-addon-docs` prember hook crashed immediately since for some reason the `e-c-typescript` dummy app is not in scope - [this.app is undefined here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/808479b7ff82b5d8e640cd8b6b617339f9178c9c/index.js#L214). I gave up and moved on to just making it work in `e-c-typescript`, which led to...

3. Prember and fastboot run, but the generated JSON file from e-c-addon-docs does not contain any routes. I fired up the Ember Data inspector to see what e-c-addon-docs has loaded in the store, and sure enough `navigationIndex` and other models in the store are empty (screenshot below). I am unsure if this issue is specific to e-c-typescript yet.

```sh
>  cat dist/docs/ember-cli-typescript.json
{"jsonapi":{"version":"1.0"},"data":{"type":"project","id":"ember-cli-typescript","attributes":{"name":"ember-cli-typescript","version":"3.0.0","navigationIndex":[]},"relationships":{"modules":{"data":[]}}}}
```

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/942358/68080799-05e2f000-fdd9-11e9-892c-a44229051f91.png">


This issue did not occur on the documentation that e-c-addon-docs itself hosts; the generated JSON file contained all of the routes (and were also visible in ember-data in the inspector, screenshot below).

```sh
> cat ../ember-cli-addon-docs/dist/docs/ember-cli-addon-docs.json 
{"jsonapi":{"version":"1.0"},"data":{"type":"project","id":"ember-cli-addon-docs","attributes":{"name":"ember-cli-addon-docs","version":"0.6.15","navigationIndex":[{"type":"components","items":[{"id":"ember-cli-addon-docs/components/docs-demo/component","path":"components/docs-demo","name":"{{docs-demo}}"},{"id":"ember-cli-addon-docs/components/docs-header/component","path":"components/docs-header","name":"{{docs-header}}"},{"id":"ember-cli-addon-docs/components/docs-hero/component","path":"components/docs-hero","name":"{{docs-hero}}"},{"id":"ember-cli-addon-docs/components/docs-keyboard-shortcuts/component","path":"components/docs-keyboard-shortcuts","name":"{{docs-keyboard-shortcuts}}"},{"id":"ember-cli-addon-docs/components/docs-link/component","path":"components/docs-link","name":"{{docs-link}}"}, <truncated>
```

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/942358/68080813-4c384f00-fdd9-11e9-822a-14409b2612a2.png">

If reading the JSON file isn't going to work for this project, we may need to result to scraping the URLs from the page sidebar...

**Comment by chriskrycho** [comment]
Becomes irrelevant as we're dropping addon-docs and moving to Gitbook.
